drop table if exists medicaments CASCADE;
drop table if exists patients CASCADE;
drop table if exists prescriptions CASCADE;
create table medicaments (id bigint generated by default as identity, exclusive_use varchar(255), max_age_consumption smallint, minimum_age_consumption smallint, name varchar(255), primary key (id));
create table patients (id bigint generated by default as identity, birth_date date not null, enabled boolean not null, gender varchar(255) not null, last_name varchar(100) not null, name varchar(100) not null, primary key (id))
create table prescriptions (id bigint generated by default as identity, date_prescription date, medicament_id bigint, patient_id bigint, primary key (id));
alter table prescriptions add constraint FK3asoi2xynomsq3wfpjpcefaia foreign key (medicament_id) references medicaments;
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients;


insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Kevin','Girata', '2022-08-27', 'MALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Felipe','Gonzalez', '1920-11-20', 'MALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Sirley','Gonzalez', '1998-11-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Dioamara','Mateus', '1998-11-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Gabriela','Girata', '1998-11-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Raquel','Bonilla', '1998-11-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Kevin','Girata', '2022-08-27', 'MALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Usuario','aaaa', '1920-11-20', 'MALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Usuario2','aaaaa', '1998-11-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Usuario3','bbbbb', '2000-10-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Usuario4','ccccc', '1970-09-20', 'FEMALE',true);
insert into patients (id, name,last_name,birth_date,gender,enabled) values (default,'Usuario5','ccccc', '2005-06-20', 'FEMALE',true);


INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Sildenafil', 18, 70, 'MALE');
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Prostatil', 18, 70, 'MALE');
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Tamoxifeno', 25, 80, 'FEMALE');
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Raloxifeno', 25, 80, 'FEMALE');
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Dolex niños', 1, 14, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Dolex fortex', 15, 75, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Atorvastatina', 18, 0, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Ibuprofeno jarabe', 0, 10, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Ibuprofeno', 10, 0, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Paracetamol jarabe', 0, 10, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Paracetamol', 10, 0, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Naproxeno', 14, 0, null);
INSERT INTO medicaments (id, name, minimum_age_consumption, max_age_consumption, exclusive_use) VALUES (default, 'Amoxicilina', 14, 0, null);